services:
  postgres-db:
    image: postgres:16-alpine
    container_name: carrito-postgres
    environment:
      POSTGRES_DB: carrito_db
      POSTGRES_USER: carrito_user
      POSTGRES_PASSWORD: carrito_password
    ports:
      - "127.0.0.1:5433:5432" # 5432 lo ocupa productos-service localmente
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carrito_user -d carrito_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
